# Not yes supported, see: https://gitlab.com/gitlab-org/gitlab/-/issues/271633

# image: java:15

# stages:
#   - build

# before_script:
#   - chmod +x gradlew

# build:
#   stage: build
#   script: ./gradlew clean build
