# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: gradle:jre15

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
 - build
 - test

api-unit-tests:
  stage: test
  script:
    - cd ./membership-management 
    - gradle test --fail-fast --tests *ServiceTest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

build-api:
  stage: build
  script:
    - cd ./membership-management
    - gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

build-logging-client:
  stage: build
  script:
    - cd ./rabbitmq-clients/logger
    - gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

build-monitoring-client:
  stage: build
  script:
    - cd ./rabbitmq-clients/monitoring
    - gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

monitoring-unit-tests:
  stage: test
  script:
    - cd ./rabbitmq-clients/monitoring
    - gradle test --fail-fast --tests *ServiceTest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
