version: '3.8'

services:

  api-container:
    build:
      context: ./membership-management
      dockerfile: Dockerfile
    container_name: api
    networks:
      - backend
    ports:
      - 8080:8080
    environment:
      - spring_rabbitmq_host=rabbitmq-container
    depends_on:
      - rabbitmq-container

  monitoring-client-container:
    build:
      context: ./rabbitmq-clients/monitoring
      dockerfile: Dockerfile
    container_name: monitoring-client
    networks: 
      - backend
    environment:
      - spring_rabbitmq_host=rabbitmq-container
    depends_on:
      - rabbitmq-container

  rabbitmq-container:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq-container
    container_name: rabbitmq
    networks:
      - backend
    ports:
      - 5672:5672
      - 15672:15672

networks:
  backend:
